main: xyz.feuxy.neon.Neon
name: Neon
version: ${version}
author: Feuxy
description: Neon is development kit for Minecraft plugins. Do not use this plugin in production environment.
softdepend: [PlugManX]
api-version: 1.13
commands:
  clear:
    description: Clear your inventory.
    aliases:
      - ci
  clearchat:
    description: Clear chat.
    aliases:
      - cc
  operator:
    description: Toggle operator mode.
    aliases:
      - o
  gmc:
    description: Change gamemode to creative.
  gms:
    description: Change gamemode to survival.
  gma:
    description: Change gamemode to adventure.
  gmsp:
    description: Change gamemode to spectator.
  day:
    description: Change time to day.
  noon:
    description: Change time to noon.
  night:
    description: Change time to night.
  midnight:
    description: Change time to midnight.
  sun:
    description: Change weather to sunny.
  rain:
    description: Change weather to rainy.
  storm:
    description: Change weather to stormy.
  fly:
    description: Toggle fly mode.
  butcher:
    description: Kill all mobs in the world.
  heal:
    description: Heal yourself.
  feed:
    description: Feed yourself.
  watchdog:
    description: Manage watchdog.
  i:
    description: Get an item.
  speed:
    description: Change your speed.
  up:
    description: Teleport an amount of blocks up.
  top:
    description: Teleport to the highest block.
  back:
    description: Teleport back to your previous location.