main: xyz.feuxy.neon.Neon
name: Neon
version: ${version}
author: Feuxy
description: Neon is development kit for Minecraft plugins. Do not use this plugin in production environment.
api-version: 1.13
commands:
  operator:
    description: Toggle operator mode.
    aliases:
      - o
  clear:
    description: Clear your inventory.
    aliases:
      - ci
  heal:
    description: Restore your health, food, and potion effects.
  butcher:
    description: Kill all entities in your world.
  gmc:
    description: Change your gamemode to creative.
  gms:
    description: Change your gamemode to survival.
  gma:
    description: Change your gamemode to adventure.
  gmsp:
    description: Change your gamemode to spectator.
  gamemode:
    description: Change your gamemode.
    aliases:
      - gm
  clearchat:
    description: Clear the chat.
    aliases:
      - cc
  day:
    description: Change the time to day.
  noon:
    description: Change the time to noon.
  night:
    description: Change the time to night.
  midnight:
    description: Change the time to midnight.
  sun:
    description: Change the weather to sunny.
  rain:
    description: Change the weather to rainy.
  storm:
    description: Change the weather to stormy.
  up:
    description: Teleport an amount of blocks up.
  speed:
    description: Change your speed.